services:
  db:
    image: postgres:16
    container_name: inventory_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    container_name: inventory_api
    depends_on:
      - db
    environment:
      DB_HOST: inventory_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: inventory
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp
    command: sh -c "./scripts/run-migrations.sh && air -c .air.toml"


volumes:
  postgres_data:
