# -------------------------
# Development Dockerfile
# -------------------------
FROM golang:1.24-alpine

# -------------------------
# Set workdir
# -------------------------
WORKDIR /app

# -------------------------
# Install dependencies
# -------------------------
RUN apk add --no-cache bash git curl make postgresql-client

# -------------------------
# Install Air for hot reload
# -------------------------
RUN go install github.com/air-verse/air@latest
ENV PATH=$PATH:/root/go/bin

# -------------------------
# Install golang-migrate
# -------------------------
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.0/migrate.linux-amd64.tar.gz \
    | tar xvz && mv migrate /usr/local/bin/


# -------------------------
# Copy project files
# -------------------------
COPY . .

# -------------------------
# Make scripts executable
# -------------------------
RUN chmod +x ./scripts/run-migrations.sh


# -------------------------
# Expose app port
# -------------------------
EXPOSE 8080

# -------------------------
# Start Air (hot reload)
# -------------------------
ENTRYPOINT ["air", "-c", ".air.toml"]
